services:
  file-sharing:
    image: file-sharing
    container_name: file-sharing-container
    restart: always
    ports:
      - '3001:3001'
    environment:
      - DB_URL=mongodb://mongo:27017/fileUpload
      - CORS_ALLOW_ORIGIN=*
      - CORS_ALLOW_METHODS=GET,POST,PUT,DELETE
      - CORS_ALLOW_HEADERS=Content-Type
    depends_on:
      - mongo
    networks:
      - mongo-compose-network
  mongo:
    container_name: mongo
    image: mongo:5.0.14
    volumes:
      - '.db:/data/db'
    ports:
      - 27017:27017
    networks:
      - mongo-compose-network
networks:
  mongo-compose-network:
    driver: bridge
